# Generated by Django 5.0.6 on 2024-06-16 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.product")),
            ],
            options={
                "verbose_name": "SubCategory",
                "verbose_name_plural": "SubCategories",
            },
        ),
        migrations.CreateModel(
            name="SubProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("sub_category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.subcategory")),
            ],
            options={
                "verbose_name": "SubProduct",
                "verbose_name_plural": "SubProducts",
            },
        ),
    ]
