version: '3.8'

services:
  backend:
    build: ./backend
    container_name: aiio_backend
    volumes:
      - ./backend:/backend
      - /backend/venv
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=DEV
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    build: ./frontend
    container_name: aiio_frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"
    expose:
      - 5173
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
  
  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django"]
      interval: 5s
      timeout: 5s
      retries: 5
